spring.application.name=AIservice

spring.data.mongodb.uri=${MongoDBChatGptAccUsedHere}
spring.data.mongodb.database=fitnessrecommendation


# Server Ports:
# userservice: 8080
# Eureka: 8761
# activityService: 8082
# ai serivce at 8084
server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
