spring.application.name=activityService

spring.data.mongodb.uri=${MongoDBChatGptAccUsedHere}
spring.data.mongodb.database=ActivityMicroservice

# Server Ports:
# userservice: 8080
# Eureka: 8761
# activityService: 8082

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
rabbitmq.exchange.name = fitness.exchange
rabbitmq.queue.name = activity
rabbitmq.routing.key = activity.tracking





