spring.application.name=EurekaServer
#because user serivce is at 8080\
#because eureKA serivce is at 8761
#because activity serivce is at 8082
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false