spring.application.name=userservice

spring.datasource.url=jdbc:postgresql://localhost:5432/microservices

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#because user serivce is at 8080\
#because eureKA serivce is at 8761
#because activity serivce is at 8082



eureka.client.service-url.defaultZone=http://localhost:8761/eureka/